name: Github Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
    pull_request:
      branches:
        - main
    schedule:
      - cron: '15 6 * * 0'
    workflow_dispatch:

    jobs:
      Build:
        runs-on: ubuntu-latest
        steps:
          - run: |
            echo "The job triggered by event: ${{ github.event_name }}"
            echo "The ref that triggered the job: ${{ github.ref }}"
          - uses: actions/checkout@v3.3.0

          - name: List files in the repo
            run: |
              echo "Listing files in the repository: ${{ github.repository}}"
              tree